### PR TITLE
Prepare `gliner` to be released on PyPI

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

## Pull Request overview
* Prepare `gliner` to be released on PyPI
  * Move most source code into `gliner` directory, except `train.py`
  * Remove `save_load.py` in favor of `GLiNER.from_pretrained` and `GLiNER.save_pretrained`
  * Add .gitignore to prevent accidentally pushing Python-related files to git
  * Add RELEASE.md document with explanations of how to release.

## Details
As discussed, this should allow you to release GLiNER on PyPI, so that people can do `pip install gliner` and `from gliner import GLiNER`. You can look over the changes in this PR, but as you can see, I only made a few.

## Next Steps

To continue development with gliner, you need to install the `gliner` package in "editable mode":
```
pip install -e .
```
This means that if you make any changes, your locally installed gliner package will be updated accordingly.

Then you can use `from gliner import GLiNER`, i.e. you can use the new updated snippet in the README.

If that all works for you locally, then you can start following the release guide. This is an admittedly fairly long document, and it took me a little while to get through it the first time, especially because it'll all be a bit new, etc. You can also just reach out for questions and I'll do my best to answer them.

- Tom Aarsen

### CODE REVIEW

**Comment by wjbmattingly** [comment]
@tomaarsen haha! no problem at all! @urchade no problem at all. It is getting late here in Kyoto and I have a few meetings in the next couple hours, so I may not be able to help any more this evening. Will check back tomorrow, though!

**Comment by tomaarsen** [comment]
No rush, it's best to just take your time with this :)

**Comment by urchade** [comment]
Hi @tomaarsen, the project is now on Pypi, but after installing it on collab, I get the following error when importing gliner: 
image

Here is the colab: https://colab.research.google.com/drive/1mhalKWzmfSTqMnR0wQBZvt9-ktTsATHB#scrollTo=3vKY3Rbj2_FC

**Comment by tomaarsen** [comment]
Let me dive into this, I probably messed this up somewhere.

**Comment by tomaarsen** [comment]
Oh, that is indeed a problem though. I made #16 to resolve the remaining things.
The core problem was that `modules` was not automatically included in the Python build.

**Pull request merged**
