### PR TITLE
adding SpaCyTokenSplitter

### PR DESCRIPTION
**Pull request by gil56**
@urchade @tomaarsen Please review:
The Problem: The `WhitespaceTokenSplitter` is not splitting properly if inside a numeric value there are commas, point or minus.
Example: text = “number 1.1 2,2 -3”
WhitespaceTokenSplitter output:
Token: ‘number’ at indices: (0, 6)
Token: ‘1’ at indices: (7, 8)
Token: ‘.’ at indices: (8, 9)
Token: ‘1’ at indices: (9, 10)
Token: ‘2’ at indices: (11, 12)
Token: ‘,’ at indices: (12, 13)
Token: ‘2’ at indices: (13, 14)
Token: ‘-’ at indices: (15, 16)
Token: ‘3’ at indices: (16, 17)
SpaCyTokenSplitter (English) output:
Token: ‘number’ at indices: (0, 6)
Token: ‘1.1’ at indices: (7, 10)
Token: ‘2,2’ at indices: (11, 14)
Token: ‘-3’ at indices: (15, 17)
solution: Support of spacy.blank by adding this class `SpaCyTokenSplitter` in the `token_splitter.py`.

Example of how to use it?
Add to the `gliner_config.json` the following keys and value: “token_splitter”: “spacy”, “token_splitter_lang”: “en”. (or any other language that spacy supports)

### CODE REVIEW

**Comment by wjbmattingly** [comment]
I really like this idea.

**Comment by urchade** [comment]
Hi @gil56, can you make installing spacy optional ? like the korean tokenizer

**Comment by gil56** [comment]
@urchade Ready after making spacy installation optional.

**Comment by urchade** [comment]
Nice thank you !

**Pull request merged**
