### PR TITLE
Add GLiNER Spacy Integration and Examples

### PR DESCRIPTION
**Pull request by wjbmattingly**
This commit introduces a new class, GLiNERPipeline, which integrates the GLiNER model with a spaCy pipeline. The integration allows for easy processing and visualization of text data using both GLiNER and spaCy functionalities.

Key features added:
- GLiNERPipeline class for wrapping GLiNER with a spaCy model.
- Automatic downloading of the spaCy model if not already installed, using spacy.cli.download.
- Implementation of the `__call__` method for processing text and generating entities.
- Support for processing large texts by dividing them into chunks and handling entity indices accordingly.
- Custom method `_create_entity_spans` to create spaCy spans from GLiNER entities.
- `visualize` method for displaying the recognized entities using spaCy's displacy.

Additional Resources:
- Updated `requirements.txt` with necessary packages.
- Added `spacy-demo.ipynb` notebook demonstrating how to use the GLiNERPipeline with spaCy.

This update enhances the usability of GLiNER by allowing users to leverage spaCy's powerful NLP tools in conjunction with GLiNER's named entity recognition capabilities.

### CODE REVIEW

**Comment by tomaarsen** [comment]
Hello!

This looks quite useful! However, I think it would be awesome if we instead could integrate GLiNER as a custom spaCy pipeline component: https://spacy.io/usage/processing-pipelines#custom-components

Then, users would have to do `nlp.add_pipe("gliner", config={"model": "...", "labels": "..."})` and then they can use spaCy like normal, as the component will remove the normal "ner" component and automatically fill the `.ents` entities in the spaCy documents! There's an example of what that looks like here:
1. The component: https://github.com/tomaarsen/SpanMarkerNER/blob/main/span_marker/spacy_integration.py#L13 (with `__call__` and `pipe`, all they really do is call the model and then `doc.set_ents(ents)`)
2. Adding it as a component: https://github.com/tomaarsen/SpanMarkerNER/blob/507740da96be620472acd256dc14d267e70bbf27/span_marker/__init__.py#L45-L66
3. Example usage: https://tomaarsen.github.io/SpanMarkerNER/notebooks/spacy_integration.html#Using-SpanMarker-models-for-Named-Entity-Recognition-with-spaCy

See also SpanMarker on spaCy: https://spacy.io/universe/project/span_marker

What do you think?

- Tom Aarsen

**Comment by wjbmattingly** [comment]
@tomaarsen Hi Tom! Thanks for the comment. This was how I originally envisioned doing it, but I wanted to keep it aligned with the author's library. I usually design custom components in these instances. If @urchade is okay with it, I will go ahead and build it with this approach instead. It won't take too long. @tomaarsen, please correct me if I am wrong, but it may be easier to then build this as a separate library? What are your thoughts?

**Comment by tomaarsen** [comment]
I'm loving your collection of spaCy-related repositories!

**Comment by wjbmattingly** [comment]
Thanks! There are quite a few. Only a few are on spaCy Universe. I need to update a few and submit a PR in the coming weeks.

**Comment by urchade** [comment]
> @tomaarsen Hi Tom! Thanks for the comment. This was how I originally envisioned doing it, but I wanted to keep it aligned with the author's library. I usually design custom components in these instances. If @urchade is okay with it, I will go ahead and build it with this approach instead. It won't take too long. @tomaarsen, please correct me if I am wrong, but it may be easier to then build this as a separate library? What are your thoughts?

I think that's a good idea as well, you can go ahead with that

**Comment by urchade** [comment]
gliner-spacy is cool for me 😎

**Comment by wjbmattingly** [comment]
Sounds great! I'm going to be setting up the repository under the TheirStory organization. If you don't mind, @urchade just ping me when you have the installation debugged and I'll get this pushed out.

**Comment by urchade** [comment]
Ok, no problem @wjbmattingly

**Comment by urchade** [comment]
Hi @wjbmattingly

**Comment by wjbmattingly** [comment]
Hi @urchade! It is live! https://pypi.org/project/gliner-spacy/0.0.1/

**Comment by stephenleo** [comment]
Thanks @wjbmattingly, it works really well! The Homepage link in PyPI is currently pointing to a 404 error: https://github.com/theirstory/gliner-spacy. Can pls update it to the correct URL?

**Comment by wjbmattingly** [comment]
Thanks for the comment @stephenleo ! The url is correct but the repository is private. TheirStory will likely making it public in the next day or so. I just wanted to get it to you all so you could test it. Once the repository is public, the README on PyPi will work just fine without a new version.

**Comment by wjbmattingly** [comment]
@urchade if you want, I can submit a new PR that updates the README to show how to use gliner-spacy. I can also submit a notebook to demo it as well.

**Comment by urchade** [comment]
Hi @wjbmattingly, thanks for gliner-spacy

sure you can do that

You can put the notebook in the example/directory

**Comment by wjbmattingly** [comment]
No problem! Thanks! I'll try and get that done today.

**Comment by wjbmattingly** [comment]
It is now fixed @stephenleo

**Comment by wjbmattingly** [comment]
@urchade I have updated the PR to include purely the documentation for using Gliner-spaCy now that gliner-spacy is a separate package. I updated the README to show the usage and added the example notebook in examples.

**Comment by ddofer** [comment]
The current example notebook seems broken? 
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[5], line 3
      1 import spacy
      2 from gliner import GLiNER
----> 3 from gliner_spacy.pipeline import GlinerSpacy

ModuleNotFoundError: No module named 'gliner_spacy'`

Running the code in the example notebook (https://github.com/urchade/GLiNER/blob/main/examples/gliner_spacy_demo.ipynb) fails

**Pull request merged**
