### PR TITLE
Addition of Morpheme-based Tokenization for Korean NER

### PR DESCRIPTION
**Pull request by taeminlee**
**Summary of Changes:**
We have introduced a new tokenization method based on morpheme analysis to improve the accuracy of the Korean Named Entity Recognition (NER) model. This addition complements the existing space-based tokenization (WhitespaceTokenizer) with a new class MecabKoTokenizer, utilizing the Mecab morpheme analyzer.

**Configuration Settings:**
gliner_config.json: This JSON file allows users to configure the tokenizer settings. The tokenizer field within this file can be used to specify the tokenizer. If no tokenizer is set, the WhitespaceTokenizer is used by default.

**Testing Information:**
Testing for the Korean NER model can be done using the model available at [taeminlee/gliner_ko](https://huggingface.co/taeminlee/gliner_ko). The gliner_config.json in that repository is set to use morphological analysis tokenizer. You can use this to test it out.

**Background:**
Korean, being an agglutinative language, presents challenges in accurate named entity recognition when tokenized only on spaces. For example, in a sentence like "서울에 가다 (Going to Seoul)," correctly identifying "서울 (Seoul)" as a location entity requires separating "서울 (Seoul)" from "서울에 (to Seoul)." This is achievable through morpheme analysis.

**Expected Impact:**
The introduction of morpheme-based tokenization is expected to significantly enhance the accuracy of the Korean NER model. Tokenization through morpheme analysis more effectively reflects the complex grammatical characteristics of Korean, enabling the model to more accurately recognize and distinguish named entities.

**Additional Information:**
This feature has been tested on extensive Korean text datasets and has shown higher accuracy compared to the existing model. Additionally, the design maintains compatibility with the existing system while incorporating new functionality.

### CODE REVIEW

**Comment by taeminlee** [comment]
I've also developed a Korean NER model, trained on a Korean NER dataset for 300,000 steps. For the span mode, `markerV0` was used. The NER tag set utilized the top 15 categories from the [TTA Tag Set](https://aiopen.etri.re.kr/data/002.%EA%B0%9C%EC%B2%B4%EB%AA%85%EC%9D%B8%EC%8B%9D_%EA%B0%80%EC%9D%B4%EB%93%9C%EB%9D%BC%EC%9D%B8.pdf). The model shows the following performance on the dev set of the konne NER dataset:

Evaluate with the [konne dev set](https://github.com/korean-named-entity/konne)

| Model                     | Precision (P) | Recall (R) | F1      |
|---------------------------|---------------|------------|---------|
| Gliner-ko (t=0.5)         | **72.51%**    | **79.82%** | **75.99%** |
| Gliner Large-v2 (t=0.5)   | 34.33%        | 19.50%     | 24.87%  |
| Gliner Multi (t=0.5)      | 40.94%        | 34.18%     | 37.26%  |
| Pororo                    | 70.25%        | 57.94%     | 63.50%  |

Sharing the GLiNER-ko model in the GLiNER repository will benefit Korean linguists and researchers. I think it would be a valuable contribution to the community. 

I would like to cautiously suggest that you could share a link to the GLiNER-ko model card in your readme.md.

**Comment by urchade** [comment]
Thank you for your contribution, 

My only concern is the naming "self.tokenizer" which could be misleading, as it is often referred to language model tokenizer. 

Maybe a name like "token_splitter" would be better

**Comment by taeminlee** [comment]
> Thank you for your contribution,
> 
> My only concern is the naming "self.tokenizer" which could be misleading, as it is often referred to language model tokenizer.
> 
> Maybe a name like "token_splitter" would be better

Thank you for your feedback. I agree that the name "tokenizer" could be misleading. I've refactored it to "token_splitter."

**Comment by urchade** [comment]
Nice, thanks!

**Pull request merged**
